version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    govet:
      enable-all: true
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      confidence: 0.1
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - revive
        text: should have a package comment, unless it's in another file for this package
formatters:
  enable:
    - gci
    - gofmt
    - goimports
